Diagnosis/Controllers/GameSessionController.cs
using Diagnosis.Models;
using Diagnosis.Models.ModelViews;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Diagnosis.Controllers
{
    public class GameSessionController : Controller
    {
        ApiController apiController;

        public GameSessionController(ApplicationContext context)
        {
            apiController = new ApiController(context);   
        }

        public ActionResult Index()
        {
            try
            {
                IActionResult? g = apiController.GetGameSessions();
                var content = g as ContentResult;
                var json = content.Content;
                var data = JsonConvert.DeserializeObject<IEnumerable<GameSession>>(json);

                return View(data);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult GetGameSession(int id)
        {
            try
            {
                IActionResult? g = apiController.GetGameSessionById(id);

                if (g != null)
                {
                    var content = g as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<GameSession>(json);

                    return View("Read", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult UpdateGameSession(int id)
        {
            try
            {
                IActionResult? g = apiController.GetGameSessionById(id);

                if (g != null)
                {
                    var content = g as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<GameSession>(json);

                    return View("Update", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateGameSession(GameSession g)
        {
            try
            {
                GameSession_EditView g_ev = new GameSession_EditView();
                g_ev.Date = g.Date;
                g_ev.Health = g.Health;
                g_ev.APM = g.APM;
                g_ev.DialogsCount = g.DialogsCount;
                g_ev.Duration = g.Duration;
                g_ev.k1 = g.k1;
                g_ev.k2 = g.k2;
                g_ev.k3 = g.k3;
                g_ev.userId = g.userId;

                apiController.EditGameSession(g_ev, g.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult DeleteGameSession(int id)
        {
            try
            {
                IActionResult? g = apiController.GetGameSessionById(id);

                if (g != null)
                {
                    var content = g as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<GameSession>(json);

                    return View("Delete", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteGameSession(GameSession g)
        {
            try
            {
                if (g != null)
                {
                    apiController.DeleteGameSession(g.Id);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult CreateGameSession()
        {
            try
            {
                return PartialView("Create");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateGameSession(GameSession g)
        {
            try
            {
                GameSession_AddView g_av = new GameSession_AddView();
                g_av.Date = g.Date;
                g_av.Health = g.Health;
                g_av.APM = g.APM;
                g_av.DialogsCount = g.DialogsCount;
                g_av.Duration = g.Duration;
                g_av.k1 = g.k1;
                g_av.k2 = g.k2;
                g_av.k3 = g.k3;
                g_av.userId = g.userId;

                apiController.AddGameSession(g_av);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
    }
}

Diagnosis/Controllers/UserController.cs
using Diagnosis.Models;
using Diagnosis.Models.ModelViews;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Diagnosis.Controllers
{
    public class UserController : Controller
    {
        ApiController apiController;

        public UserController(ApplicationContext context)
        {
            apiController = new ApiController(context);
        }

        public IActionResult Index()
        {
            try
            {
                IActionResult? u = apiController.GetUsers();
                var content = u as ContentResult;
                var json = content.Content;
                var data = JsonConvert.DeserializeObject<IEnumerable<User>>(json);

                return View(data);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult GetUser(int id)
        {
            try
            {
                IActionResult? u = apiController.GetUserById(id);

                if (u != null)
                {
                    var content = u as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<User>(json);

                    return View("Read", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult UpdateUser(int id)
        {
            try
            {
                IActionResult? u = apiController.GetUserById(id);

                if (u != null)
                {
                    var content = u as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<User>(json);

                    return View("Update", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateUser(User u)
        {
            try
            {
                User_EditView u_ev = new User_EditView();
                u_ev.Name = u.Name;
                u_ev.Free = u.Free;
                u_ev.PredeterminedDiagnosis = u.PredeterminedDiagnosis;

                apiController.EditUser(u_ev, u.Id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult DeleteUser(int id)
        {
            try
            {
                IActionResult? u = apiController.GetUserById(id);

                if (u != null)
                {
                    var content = u as ContentResult;
                    var json = content.Content;
                    var data = JsonConvert.DeserializeObject<User>(json);

                    return View("Delete", data);
                }

                return View("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUser(User u)
        {
            try
            {
                if (u != null)
                {
                    apiController.DeleteUser(u.Id);
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public ActionResult CreateUser()
        {
            try
            {
                return PartialView("Create");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(User u)
        {
            try
            {
                User_AddView u_av = new User_AddView();
                u_av.Name = u.Name;
                u_av.Free = u.Free;
                u_av.PredeterminedDiagnosis = u.PredeterminedDiagnosis;

                apiController.AddUser(u_av);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
    }
}

Diagnosis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diagnosis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Diagnosis.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Diagnosis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Глваная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GameSession" asp-action="Index">Игровые сессии</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Пользователи</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Diagnosis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>